CATEGORY_MAPS = {
    "You agree to indemnify and hold the service harmless in case of a claim related to your use of the service": "You agree to defend, indemnify, and hold the service harmless in case of a claim related to your use of the service",
    "Defend, indemnify, hold harmless; survives termination": "You agree to defend, indemnify, and hold the service harmless in case of a claim related to your use of the service",
    "The service does not use any third-party advertising services": "No third-party analytics or tracking platforms are used",
    "The service does not use any third-party advertising services": "No third-party analytics or tracking platforms are used",
    "Only for your individual use": "This service is only available for use individually and non-commercially",
    "Your personal data is used for advertising": "Your personal or sensitive data is used for targeted advertising, including third-party and identity-based ads",
    "Your personal data is used to employ targeted third-party advertising": "Your personal or sensitive data is used for targeted advertising, including third-party and identity-based ads",
    "Sensitive data is collected and shared to target advertising": "Your personal or sensitive data is used for targeted advertising, including third-party and identity-based ads",
    "Your identity is used in ads that are shown to other users": "Your personal or sensitive data is used for targeted advertising, including third-party and identity-based ads",
    "Terms may be changed any time at their discretion, without notice to you": "Terms may be changed at any time",
    "The terms may be changed at any time, but you will receive notification of the changes": "Terms may be changed at any time",
    "When the service wants to change its terms, you are notified a week or more in advance.": "Terms may be changed at any time",
    "Instead of asking directly, this Service will assume your consent to changes of terms merely from your usage.": "Terms may be changed at any time",
    "Your IP address is collected, which can be used to view your approximate location": "Your location may be collected, used or shared, whether precisely or approximately, using IP address, GPS, or other device signals.",
    "This service may collect, use, and share location data": "Your location may be collected, used or shared, whether precisely or approximately, using IP address, GPS, or other device signals.",
    "This service receives your precise location through GPS coordinates": "Your location may be collected, used or shared, whether precisely or approximately, using IP address, GPS, or other device signals.",
    'Do Not Track (DNT) headers are ignored and you are tracked anyway even if you set this header.': "This service does not honor 'Do Not Track' (DNT) headers",
    "Your browser's Do Not Track (DNT) headers are respected": "This service honors 'Do Not Track' (DNT) headers",
}
